name: publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish job
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: generate TS protobuf
        run: yarn run generate

      - name: publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

